#!/bin/bash
pushd ~/jaws-training
git checkout master
git merge development
ojet build web --release
git add --all .
git commit -a -m "After release build on master branch."
git push origin master
popd
